image: node:latest

stages:
  - setup
  - test
  - release
  - build
  - publish

install:
  stage: setup
  only:
    - merge_requests
    - master
  script:
    - yarn install --force
  artifacts:
    paths:
      - node_modules/
    expire_in: 2h

prettier:
  stage: test
  only:
    - merge_requests
  script:
    - yarn prettier:check

lint:
  stage: test
  only:
    - merge_requests
  script:
    - yarn lint

release:
  stage: release
  only:
    - master
  except:
    - 'v[0-9]+.[0-9]+.[0-9]+*'
  before_script:
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git config receive.advertisePushOptions true
    - git remote set-url origin https://gitlab-ci-token:rqZxrs9cjyNsNLGUcCzd@gitlab.vitta.tools/front-end/$CI_PROJECT_NAME.git
    - git checkout $CI_COMMIT_BRANCH
  script:
    - git pull --rebase origin $CI_COMMIT_BRANCH
    - yarn release
    - git push --follow-tags origin $CI_COMMIT_BRANCH
    - git fetch
    - git checkout develop
    - git rebase $CI_COMMIT_BRANCH
    - git push origin develop

build:
  stage: build
  on:
    push:
      tags:
        - 'v[0-9]+.[0-9]+.[0-9]+*'
  script:
    - yarn build
  artifacts:
    paths:
      - lib/
    expire_in: 1h

publish:
  stage: publish
  on:
    push:
      tags:
        - 'v[0-9]+.[0-9]+.[0-9]+*'
  script:
    - yarn publish --verbose
