image: node:latest

stages:
  - setup
  - test
  - release
  - build
  - publish

install:
  stage: setup
  only:
    - merge_requests
    - master
    - /^v\d+.\d+.\d+/
  script:
    - yarn install --force
  artifacts:
    paths:
      - node_modules/
    expire_in: 2h

prettier:
  stage: test
  only:
    - merge_requests
  script:
    - yarn prettier:check

lint:
  stage: test
  only:
    - merge_requests
  script:
    - yarn lint

release:
  stage: release
  only:
    - master
  except:
    - tags
  before_script:
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git remote set-url origin https://gitlab-ci-token:rqZxrs9cjyNsNLGUcCzd@gitlab.vitta.tools/front-end/$CI_PROJECT_NAME.git
  script:
    - git fetch
    - git checkout develop
    - yarn release
    # - git push origin --tags
    - git push --follow-tags origin develop
    # - git fetch --tags --force
    # - git rebase $(git describe --tags $(git rev-list --tags --max-count=1))
    # - git push origin develop --no-verify -f
    - git pull origin develop
    - git checkout $CI_COMMIT_BRANCH
    - git pull origin $CI_COMMIT_BRANCH
    - git merge develop
    - git push origin $CI_COMMIT_BRANCH -o ci.skip --no-verify

build:
  stage: build
  only:
    - /^v\d+.\d+.\d+/
  script:
    - yarn build
  artifacts:
    paths:
      - lib/
    expire_in: 1h

publish:
  stage: publish
  only:
    - /^v\d+.\d+.\d+/
  script:
    - yarn publish --verbose
