image: node:latest

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

stages:
  - setup
  - test
  - release
  - build
  - publish

install:
  stage: setup
  only:
    - merge_requests
    - /release\/\d+\.\d+\.\d+/
    - master
  script:
    - yarn install --force
  artifacts:
    paths:
      - node_modules/
    expire_in: 2h

prettier:
  stage: test
  only:
    - merge_requests
  script:
    - yarn prettier:check

lint:
  stage: test
  only:
    - merge_requests
  script:
    - yarn lint

release:
  stage: release
  only:
    - master
  before_script:
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git config receive.advertisePushOptions true
    - git remote set-url origin https://gitlab-ci-token:rqZxrs9cjyNsNLGUcCzd@gitlab.vitta.tools/front-end/$CI_PROJECT_NAME.git
    - git checkout $CI_COMMIT_BRANCH
  script:
    - git pull --rebase origin $CI_COMMIT_BRANCH
    - yarn release
    - git push --follow-tags origin "$CI_COMMIT_BRANCH"
    - git checkout develop
    - git rebase master
    - git push origin develop

build:
  stage: build
  only:
    - /release\/\d+\.\d+\.\d+/
  script:
    - yarn build
  artifacts:
    paths:
      - lib/
    expire_in: 1h

publish:
  stage: publish
  only:
    - /release\/\d+\.\d+\.\d+/
  script:
    - yarn publish --verbose
